### ISSUE TITLE
new Font() should check for font existance and return undefined

### ISSUE THREAD

**Issue by FreshXOpenSource** [zetsingithub/node-sdl2-ttf#1]
in my code if i run
```
const font = new Font('non existing font file');
if(!font){
    console.log('Font not found!');
} else {
    console.log(font);
}
```
results in
```
font {
  _font: <Buffer >,
  file: 'non existing font file',
  fontface: fontface { font: [Circular] } 
}```

using this font later in the code harshly crashes the whole node process with a segfault

**Comment by zetsin** [comment]
I can not return undefined from `new Font`, because `Font` is a `Class` in ES6.
So, you can check `font._font.length` which is the underlying pointer.
Of cause I could add a method into `Font` to do the same thing.

What's your suggestion and why you use this module which I just created for my another project called node-sdl2 ?

**Comment by FreshXOpenSource** [comment]
we're using both together, node-sdl2 and sdl2-ttf and i tracked down the segfault to this module so i report here

from an outside (of the sdl2-ttf/node-sdl2 module) perspective i think either the font creation with new Font() should report an failure (which seems not straightforward according the mentioned problem above) alternatively all calling methods of the font object should check if the font object is valid and return with an error if not.

btw, thanks a lot for the work on node-sdl2 and the related submodules!

**Comment by zetsin** [comment]
Fixed.

BTW, I have made another binding of [GUI library **libui**](https://github.com/andlabs/libui), I think it's better than SDL2.

If you are interested, I would like to supply document for [it](https://github.com/zetsin/lib-ui).

**Comment by FreshXOpenSource** [comment]
thanks for the fix! 

we are currently not developing a gui based system, but thanks for the note!
